apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-fraud-detection-config
data:
  FRAUD_RULES_AMOUNT_DENY_THRESHOLD: "10000"
  FRAUD_RULES_AMOUNT_REVIEW_THRESHOLD: "5000"
  FRAUD_RULES_APPROVE_RISK_SCORE: "0.1"
  GRPC_SERVER_EXECUTOR_CORE_THREADS: "2"
  GRPC_SERVER_EXECUTOR_MAX_THREADS: "8"
  GRPC_SERVER_EXECUTOR_KEEP_ALIVE_SECONDS: "60"
  GRPC_SERVER_EXECUTOR_QUEUE_TYPE: "array"
  GRPC_SERVER_EXECUTOR_QUEUE_CAPACITY: "1024"
  GRPC_SERVER_EXECUTOR_ALLOW_CORE_TIMEOUT: "false"
  SQS_ENABLED: "true"
  SQS_QUEUE_URL: "<transactions_queue_url>"
  SQS_REGION: "us-east-1"
  OUTBOX_ENABLED: "true"
  OUTBOX_TABLE_NAME: "fintech-outbox"
  OUTBOX_DECISION_QUEUE_URL: "<decisions_queue_url>"
  OUTBOX_REGION: "us-east-1"
