apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintech-fraud
resources:
  - ../../base
images:
  - name: fintech-fraud-detection
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/fintech-fraud-detection
    newTag: latest
patches:
  - path: service-patch.yaml
