apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintech-fraud
resources:
  - ../../base
images:
  - name: fintech-fraud-detection
    newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/fintech-fraud-detection
    newTag: latest
patches:
  - path: service-patch.yaml
