apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-for-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-for-fluent-bit
subjects:
  - kind: ServiceAccount
    name: aws-for-fluent-bit
    namespace: amazon-cloudwatch
