apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-for-fluent-bit
  namespace: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::238479991718:role/eksctl-fintech-fraud-addon-iamserviceaccount--Role1-bDcEvbavWYqp%%
